# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Get Off Better.'
display_title:    'Mindful Masturbation: Get Off Better'
tagline:          'A Jekyll theme'
description:      'Masturbation can be so much more. Unlock amazing self-love!'
url:              'https://mindfulmasturbation.space'
baseurl:          '/'

plugins:
  - jekyll-sitemap
